# Generated by Django 6.0.7 on 2026-09-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
