# Generated by Django 6.0.7 on 2026-08-14 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('attendee', 'Attendee'), ('organizer', 'Organizer')], default='attendee', max_length=20)),
                ('email_verification_code_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_verification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('email_verification_resend_count', models.PositiveIntegerField(default=0)),
                ('email_verification_cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
