# Generated by Django 6.0.7 on 2026-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_google_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_token_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
